### ISSUE TITLE
Butterfly关于页面魔改

### ISSUE THREAD

**Issue by HiPeach** [zhheo/hexo-butterfly-editor#13]
- 分类：页面-关于
- 链接：https://opeach.cn/posts/dab4.html
- 作者：HiPeach
- 引语：
如你所见，这篇教程大多转自[安知鱼的文章](https://anzhiy.cn/posts/e62b.html)
但是，如果**完全按照知鱼的教程**进行魔改
就会发现一个很大的问题——致谢板块的打赏按钮无法使用
为此12月21日一整天，我都在找解决方案...
- 我做了什么：完善打赏按钮（扒下知鱼的样式，自己实现其功能，详见文章内心路历程）

**Comment by zhheo** [comment]
已添加，近期更新
