### ISSUE TITLE
一些魔改教程

### ISSUE THREAD

**Issue by EmptyDreams** [zhheo/hexo-butterfly-editor#14]
类型比较杂，希望可以选一些合适的放上去。

1. 侧边栏卡片选择器
    使用纯 CSS 实现侧边栏卡片选择器，效果见 [山岳库博 - 主页](https://kmar.top/)。
    URL：https://kmar.top/posts/5c06ceee/

2. 小白也能用的 SW 构建插件
    自动为网站构建 ServiceWorker，支持本地缓存管理、URL 重定向，完美兼容 pjax，理论上全主题通用。
    URL：https://kmar.top/posts/73014407/

3. 纯 CSS 实现超长文本轮回滚动
    短文本固定不动，长文本左右滚动显示。
    URL：https://kmar.top/posts/9db1c87c/

4. 在开启 Pjax 的情况下实现缓存的更新
    启用 Pjax 后，在不需要用户手动刷新页面的前提下更新指定标签，主要用于手动管理本地缓存，也可以用于重新执行指定 JS。
    URL：https://kmar.top/posts/40941fca/

5. 给博客添加自定义的通知悬浮窗
    用自定义的悬浮窗替代 btf 自带的悬浮窗，悬浮窗有以下特点：
    + 可使用鼠标或代码手动关闭
    + 鼠标悬浮重置自动关闭倒计时
    + 可同时显示多个悬浮窗
    + 无第三方依赖
    + 全主题通用

    URL：https://kmar.top/posts/de06ec72/

**Comment by zhheo** [comment]
在开启Pjax的情况下实现缓存的更新
给博客添加自定义的通知悬浮窗
已收录，近期更新
