### ISSUE TITLE
Ecx-UI魔改

### ISSUE THREAD

**Issue by Ezgx** [zhheo/hexo-butterfly-editor#17]
https://ezgx.tk/posts/22100/ --顶栏
https://ezgx.tk/posts/64874/ --文章板块+文章页
https://ezgx.tk/posts/6854/ --页脚侧边栏
https://ezgx.tk/posts/47635/ --速度优化-css预加载大尺寸的css

**Comment by xlenco** [comment]
six six 大佬审美太好了，我不配看

**Comment by so1ve** [comment]
丑的要死

**Comment by am-abudu** [comment]
非常有特色的界面，令人印象深刻

**Comment by so1ve** [comment]
英雄联盟✌
非常好工作👍
爱来自瓷器❤

**Comment by zhheo** [comment]
速度优化-css预加载大尺寸的css
已收录，近期更新

**Comment by oCoke** [comment]
lol. a great work, ❤️ from 🇨🇳 .
