### ISSUE TITLE
添加阅读统计与Action部署

### ISSUE THREAD

**Issue by GC-ZF** [zhheo/hexo-butterfly-editor#18]
page.md 统计
教程地址：[hexo-hot-article](https://zhangshier.vip/posts/12205/)
阅读排行：基于百度统计实现网站的访客数量、阅读文章、访客地图的三个统计图
[实际效果](https://zhangshier.vip/hot-article/)

efficiency.md 推送
教程地址：[Hexo 自动化部署](https://zhangshier.vip/posts/8779/)
Github Action部署方案：主要是方案三的方法
原方案二中包含Gitee Page部署，没什么用在方案三中剃掉了
方案三中包含私有仓库推送Github Page、服务器、Gitee二次私有备份以及SEO（借助乐特的插件实现）、CDN的刷新

这个不知道属于哪类，还得请洪哥分个类
教程地址：[Twikoo 评论定时备份方案](https://zhangshier.vip/posts/33638/)
这个适用性可能不高，仅面对vercel部署的

**Comment by zhheo** [comment]
网站无法访问

**Comment by GC-ZF** [comment]
> 网站无法访问

洪哥，昨天改了好多东西下午网站乱了然后把解析给关了（现在颜色也略有些乱...），现在开开了，抱歉哇
