### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by sysfox** [zhheo/hexo-butterfly-editor#2]
以下仅代表个人意见：
1. 可以用js.org项目或js.cool项目，现在这个域名太长了
2. 建议在每一个链接下方添加适配的Butterfly版本(工程量可能极大)

**Comment by LYXOfficial** [comment]
jsorg jscool的速度较慢，且本域名并不难记。
不过适配版本的话可以让洪哥搞搞（目测会摆烂）

**Comment by sysfox** [comment]
这个域名我觉得打出来的话太长了，不改的话唯一的解决方法就是推广，让大家把这个链接加到博客的友链里

**Comment by sysfox** [comment]
而且js.org和js.cool并不必须配置cf加速，可以只是把域名绑到vercel上，反正我的博客就是这么搞得

**Comment by sysfox** [comment]
话说洪哥都不看issue的吗

**Comment by zhheo** [comment]
因为不准备考虑用户会自己手动输入域名的场景，所以暂无此计划。
添加版本应该不是我来做的，而是作者在文章中自行更新文章，这个文档主要是方便快速找教程的索引用处。
比如店长站访问太卡了，所以就直接用文档进比较快。

**Comment by sysfox** [comment]
哦^o^
