### ISSUE TITLE
Hexo插件 | 直接复制markdown | 一秒转载

### ISSUE THREAD

**Issue by charles-hsuz** [zhheo/hexo-butterfly-editor#28]
一个Hexo插件，允许你直接从网页复制markdown，主要为butterfly主题开发，但基本的复制功能是通用的。

**Comment by charles-hsuz** [comment]
https://www.crowhsu.top/posts/6e818316.html?_sw-precache=83575f0c05e0f26a4f7a4eb6257822a1

**Comment by charles-hsuz** [comment]
https://www.crowhsu.top/posts/6e818316.html

**Comment by zhheo** [comment]
已添加，近期更新
