### ISSUE TITLE
修复 Vercel/Github Actions 部署 hexo 导致文章的更新时间错误

### ISSUE THREAD

**Issue by 0ojixueseno0** [zhheo/hexo-butterfly-editor#29]
https://blog.im0o.top/posts/c6d9de72.html
desc: `在使用 Vercel 或 Github Actions 自动化部署 hexo 博客时会发现所有文章的更新时间都变成了此次提交修改的时间，本文将介绍如何修复这个问题。`

**Comment by zhheo** [comment]
已添加，近期更新
