### ISSUE TITLE
侧边栏破坏小飞机

### ISSUE THREAD

**Issue by DreamCollector** [zhheo/hexo-butterfly-editor#50]
+ 分类：侧边栏-侧边栏组件
+ 标题：侧边栏破坏小飞机
+ 链接：https://blog.pzai.cloud/posts/1e3a940e/
+ 作者：Pzai
> 逛博客不得有个有趣的小游戏，看不顺眼就通通消灭~（由于需要键盘操作，所以只能在网页端玩，但是真的上瘾）

**Comment by zhheo** [comment]
已收录
