### ISSUE TITLE
半方池水半方田一些文章申请收录

### ISSUE THREAD

**Issue by uuanqin** [zhheo/hexo-butterfly-editor#53]
- 分类：侧边栏-侧边栏组件
- 标题：ButterFly不改动主题源码实现自定义侧边栏
- 链接：https://uuanqin.top/p/568ad08/
- 作者：wuanqin
---

- 分类：页脚-组件
- 标题：Butterfly自定义页脚（不修改主题源码）
- 链接：https://uuanqin.top/p/91b7dad/
- 作者：wuanqin
---

- 分类：页面-页面定制修改
- 标题：Butterfly夜间模式变换网站图标
- 链接：https://uuanqin.top/p/f06d4de6/
- 作者：wuanqin
---

- 分类：文章-评论美化
- 标题：为评论系统增加输入提醒【Waline】
- 链接：https://uuanqin.top/p/b3be711f/
- 作者：wuanqin
（文章建议放在 _**给你的评论添加一个输入提醒吧\-Leonus**_ 之后，改进点在于直接针对Waline评论系统与填坑，省去摸索时间）
---

- 分类：效率-推送
- 标题：将CDN缓存自动刷新加入到Hexo博客发布的工作流
- 链接：https://uuanqin.top/p/b05ac1ee/
- 作者：wuanqin
---

- 分类：效率-写作
- 标题：构建Obsidian的Hexo写作工作流
- 链接：https://uuanqin.top/p/51890a9/
- 作者：wuanqin

**Comment by zhheo** [comment]
已收录
