### ISSUE TITLE
链接失效

### ISSUE THREAD

**Issue by W1ndys** [zhheo/hexo-butterfly-editor#62]
![image](https://github.com/zhheo/hexo-butterfly-editor/assets/109416673/c05ce82c-885a-42d6-a90c-0dc6b7e964f6)
![image](https://github.com/zhheo/hexo-butterfly-editor/assets/109416673/ffcdbb14-6092-4405-ab73-d7c8bd2f6433)

**Comment by zhheo** [comment]
久等啦，已移动到error页面，会在今日更新

**Comment by W1ndys** [comment]
> 久等啦，已移动到error页面，会在今日更新

谢谢！！
