### ISSUE TITLE
【请求添加】博客全局快捷键的简陋实现

### ISSUE THREAD

**Issue by RicharPao** [zhheo/hexo-butterfly-editor#63]
标题：博客全局快捷键的简陋实现
作者：VacuolePao
链接：https://vacuole.top/p/9110baec.html
分类：功能-功能开发
描述：使用Javascript简单实现快捷键功能，肯定能用，但是丐版，没用洪哥的快捷键窗口

**Comment by zhheo** [comment]
已添加，会在今日更新
