### ISSUE TITLE
为博客添加一个游戏收藏页（npm插件版）

### ISSUE THREAD

**Issue by SinzMise** [zhheo/hexo-butterfly-editor#65]
标题：为博客添加一个游戏收藏页（npm插件版）
作者：王九弦SZ·Ninty
链接：https://blog.sinzmise.top/posts/10045/
分类：页面-其他
描述：基于Kouseki版本的[为博客添加一个游戏收藏页](https://blog.kouseki.cn/posts/e7dd.html)所做的npm插件版

**Comment by zhheo** [comment]
已添加，预计今日更新
