### ISSUE TITLE
[投稿文章] 

### ISSUE THREAD

**Issue by W1ndys** [zhheo/hexo-butterfly-editor#67]
标题：使用 Netlify，cloudflare pages，GitHub pages , Vercel ，Render部署你的 Hexo
作者：W1ndys
链接：https://blog.w1ndys.top/posts/fbbdb8eb.html
分类：部署
描述：使用 Netlify，cloudflare pages，GitHub pages , Vercel ，Render部署你的 Hexo

**Comment by dreamerhe114514** [comment]
标题：Markdown书写教程
作者：小何
链接：https://hexo.dreamerhe.qianxun7747.eu.org/posts/53128/
分类：从零开始,文章
描述：Markdown书写格式

**Comment by dreamerhe114514** [comment]
标题：Markdown书写教程
作者：小何
链接：https://hexo.dreamerhe.qianxun7747.eu.org/posts/53128/
分类：从零开始,文章
描述：Markdown书写格式

**Comment by W1ndys** [comment]
@dreamerhe114514 兄弟，你发在我的评论区了，你新开个issues吧

**Comment by dreamerhe114514** [comment]
> @dreamerhe114514 兄弟，你发在我的评论区了，你新开个issues吧
抱歉抱歉，第一次提交没经验哈

**Comment by W1ndys** [comment]
> > @dreamerhe114514 兄弟，你发在我的评论区了，你新开个issues吧
> > 抱歉抱歉，第一次提交没经验哈

哈哈哈没事，我不介意，只是提醒你一下，不然的话，洪哥也不太方便合并议题

**Comment by dreamerhe114514** [comment]
> > > @dreamerhe114514 兄弟，你发在我的评论区了，你新开个issues吧
> > > 抱歉抱歉，第一次提交没经验哈
> 
> 哈哈哈没事，我不介意，只是提醒你一下，不然的话，洪哥也不太方便合并议题

好的好的，多谢了，加个友链？

**Comment by W1ndys** [comment]
> > > > @dreamerhe114514 兄弟，你发在我的评论区了，你新开个issues吧
> > > > 抱歉抱歉，第一次提交没经验哈
> > 
> > 
> > 哈哈哈没事，我不介意，只是提醒你一下，不然的话，洪哥也不太方便合并议题
> 
> 好的好的，多谢了，加个友链？

我的荣幸，我的：https://blog.w1ndys.top/link/#%E6%B3%95%E4%B8%80-pull-request-%E6%9C%89-github-%E5%9F%BA%E7%A1%80%E7%9A%84%E6%8E%A8%E8%8D%90%E7%94%A8%E6%AD%A4%E6%96%B9%E6%B3%95
可以直接申请pr，（首次加载可能有点……慢，换流量或者开魔法可以提高加载速度）

**Comment by dreamerhe114514** [comment]
> > > > > @dreamerhe114514 兄弟，你发在我的评论区了，你新开个issues吧
> > > > > 抱歉抱歉，第一次提交没经验哈
> > > 
> > > 
> > > 哈哈哈没事，我不介意，只是提醒你一下，不然的话，洪哥也不太方便合并议题
> > 
> > 
> > 好的好的，多谢了，加个友链？
> 
> 我的荣幸，我的：https://blog.w1ndys.top/link/#%E6%B3%95%E4%B8%80-pull-request-%E6%9C%89-github-%E5%9F%BA%E7%A1%80%E7%9A%84%E6%8E%A8%E8%8D%90%E7%94%A8%E6%AD%A4%E6%96%B9%E6%B3%95 可以直接申请pr，（首次加载可能有点……慢，换流量或者开魔法可以提高加载速度）
我的
- name: 追梦境
  link: https://hexo.dreamerhe.qianxun7747.eu.org/
  avatar: https://hexo.dreamerhe.qianxun7747.eu.org/LOGO/logo.png
  descr: 梦境之浩瀚，追寻之困难，努力之辛苦，实现之甘甜!
  siteshot: https://image.thum.io/get/allowJPG/wait/20/width/600/crop/950/https://hexo.dreamerhe.qianxun7747.eu.org/

**Comment by W1ndys** [comment]
@dreamerhe114514 
已添加
我的
```
- name: W1ndysの小屋
  link: https://blog.w1ndys.top/
  avatar: https://blog.w1ndys.top/img/about/avatar.png
  descr: 欲戴皇冠，必承其重
```

**Comment by zhheo** [comment]
发现pr中有相同的重复提交，本条已忽略

**Comment by W1ndys** [comment]
> 发现pr中有相同的重复提交，本条已忽略

可以，感谢洪哥

> 从浏览到反馈再到参与pr哈哈哈，成长了
