### ISSUE TITLE
[投稿文章] 

### ISSUE THREAD

**Issue by dreamerhe114514** [zhheo/hexo-butterfly-editor#68]
标题：Markdown书写教程
作者：小何(Dreamerhe)
链接：https://hexo.dreamerhe.qianxun7747.eu.org/posts/53128/
分类：从零开始-文章
描述：Markdown书写格式

**Comment by zhheo** [comment]
中国大陆网络环境下无法访问，本条已忽略
<img width="751" alt="image" src="https://github.com/zhheo/hexo-butterfly-editor/assets/33177975/713d201c-11d6-4af4-88dd-a46372dd01e2">
