### ISSUE TITLE
[投稿文章] 

### ISSUE THREAD

**Issue by willow-god** [zhheo/hexo-butterfly-editor#70]
标题：基于店长样式的友链页重构及魔改后友链朋友圈适配
作者：清羽飞扬
链接：https://blog.qyliu.top/posts/59fe844d/
分类：友情链接-样式
描述：店长的五种友链卡片都整合到了一起，结合安知鱼的教程，最终实现了“五世同堂”友链页面，五种友链可以随便混合搭配，针对鱼佬的友链美化后无法适配友链朋友圈的抓取规则，提供了一个相对可行解决方案。实测无服务器部署和自行部署均可正常抓取，同时稍微改造将原生友链页面中的随机顺序功能又添加了进来。

**Comment by zhheo** [comment]
已添加，预计今日更新
