### ISSUE TITLE
[投稿文章] 

### ISSUE THREAD

**Issue by willow-god** [zhheo/hexo-butterfly-editor#71]
标题：关于页简单魔改
作者：LiuShen
链接：https://blog.qyliu.top/posts/8f52e732/
分类：页面-关于
描述：关于页面，就相当于一个站点的门户，只有这里才能让访客了解站长，原本的关于页面丑的简直没法看，干巴巴的文字，一点动效都没有，上网查找了一些相关教程，但是都没有满意的，要么就是太复杂，要么就是太花哨，不是说不好看，而是不适合我的站点。而现在，虽然不能说精通，但是好歹也算学过一点点知识了，那么我们就尝试着自己搞搞，看看能不能整一个心仪的出来吧！

**Comment by zhheo** [comment]
已添加，预计今日更新
