### ISSUE TITLE
[投稿文章] 自建萌萌的Moe-Counter计数器并使用

### ISSUE THREAD

**Issue by dreamerhe114514** [zhheo/hexo-butterfly-editor#74]
标题：自建萌萌的Moe-Counter计数器并使用
作者：何星梦
链接：https://hexo.dreamerhe.cn/posts/6423/
分类：侧边栏-侧边栏组件
描述：使用MongoDB和Vercle部署萌萌的博客访问计数器并在侧边栏显示

**Comment by zhheo** [comment]
已添加，预计今日更新
