### ISSUE TITLE
[投稿文章] 安全跳转页面·插件版

### ISSUE THREAD

**Issue by willow-god** [zhheo/hexo-butterfly-editor#76]
标题：安全跳转页面·插件版
作者：LiuShen
链接：https://blog.qyliu.top/posts/1dfd1f41/
分类：功能-功能开发（我也不知道该不该放到哪里，洪哥帮我找个地方塞着QAQ）
描述：基于hexo-external-link，二次开发的外链跳转页插件，实现真正的替换，在生成静态文件时进行替换，而不是之前的通过JS进行匹配并替换，支持`CSS`选择器选择特定窗口，支持`Base64`编码加密目标地址，支持一定程度的简单自定义，如头像，副标题，暗黑模式，如果有前端基础，还可以通过修改源文件进行自定义美化。

**Comment by willow-god** [comment]
标题：Github Action实现友链状态检测
作者：LiuShen
链接：https://blog.qyliu.top/posts/c2262998/
分类：功能-功能开发
描述：自动化检测友链状态的方法，使用GitHub Action来定时执行Python脚本，以检查友链的可达性。系统能够输出检测结果到控制台，并将结果保存在result.json文件中。此外，还提供了一个前端展示界面，除此之外，还可以通过API接口可以获取友链的可达性数据，并以小标签方式展示到友链页面每个卡片左上角。

**Comment by zhheo** [comment]
预计今日更新
