### ISSUE TITLE
[投稿文章] Waline 评论区实现外链跳转中间页

### ISSUE THREAD

**Issue by uuanqin** [zhheo/hexo-butterfly-editor#77]
标题：Hexo 博客与 Waline 评论区实现外链跳转中间页
作者：wuanqin
链接：https://uuanqin.top/p/e1ee5eca/
分类：文章-评论
描述：安装博主自写插件实现 Waline 评论区外部链接跳转到中间页。利用插件的拓展功能可定制中间页链接格式，以配合其他的中间页插件。

**Comment by zhheo** [comment]
已发现相关pr
